cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),  #왜 얘는 인트값으로 안 받을까?
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <title>{% block title %}{% endblock %}</title>


   <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


   <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
 integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}
<!-- 블록 뭐인지 ?? -->
    {% block style %}
    {% endblock %}
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
   <a class="navbar-brand" href="/"><h3>Ebony Books</h3></a>
   <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
     <li class="nav-item active">
       <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">Link</a>
     </li>
     <li class="nav-item">
       <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
     </li>
   </ul>
   <form class="form-inline my-2 my-lg-0">
     <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
     <button class="btn btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
   </form>
   <ul class="navbar-nav justify-content-end">
     <li class="nav-item">
         {% if user.is_authenticated %}
             <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
         {% else %}
             <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
         {% endif %}
     </li>

     <li class="nav-item active"></a>
       <a class="nav-link btn btn-online-success" href="{% url 'cart:detail' %}">장바구니
         {% if cart|length > 0 %}
           ({{cart|length}})
         {% else %}
           ({{cart|length}})
         {% endif %}
       </a>
     </li>

 </div>
      <!-- <a class="navbar-brand" href="/"><h1>Ebony Books</h1></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
     aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
                {% else %}
                    <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
                {% endif %}
            </li>

            <li class="nav-item active"></a>
              <a class="nav-link btn btn-online-success" href="{% url 'cart:detail' %}">장바구니
                {% if cart|length > 0 %}
                  ({{cart|length}})
                {% else %}
                  ({{cart|length}})
                {% endif %}
              </a>
            </li>

        </ul>
      </div> -->
    </nav>
  </header>


<div class="container">
{% block content %}
{% endblock %}
</div>


</body>
</html>